### 1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])

In [3]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица D:\n{D}')
print(f'\nМатрица U:\n{U}')
print(f'\nМатрица V:\n{V}')

Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]

Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


- проверка полученных матриц

In [5]:
print(np.around(np.dot(V.T, V)))

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [6]:
print(np.around(np.dot(np.dot(U, D), V.T)))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


### 2. Для матрицы из предыдущего задания найти:

   #### а) евклидову норму;
    
   #### б) норму Фробениуса.

### * Норма Евклида

In [7]:
NormE = np.linalg.norm(A, ord=2) 
print(f'Норма Евклида для матрицы А:\n{NormE}')

Норма Евклида для матрицы А:
8.824868854820444


норма полученная при помощи функции __np.linalg.norm__ равна $\mu_{1}$ матрицы D

In [8]:
np.around(NormE, decimals = 5) == np.around(D[0,0], decimals = 5)

True

### * Норма Фробениуса <br>
#### Cпособ №1

In [9]:
NormF = np.linalg.norm(A, ord='fro') 
print(f'Норма Фробениуса для матрицы А:\n{NormF}')

Норма Фробениуса для матрицы А:
11.045361017187261


 #### Cпособ №2

In [10]:
B = (A*A)
NormF_A = np.sqrt(np.array([el.sum() for el in B]).sum())
print(f'Норма Фробениуса для матрицы А:\n{NormF_A}')


Норма Фробениуса для матрицы А:
11.045361017187261


норма полученная при помощи функции __np.linalg.norm__ равна $$ \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^{2}}$$

In [11]:
np.around(NormF, decimals = 5) == np.around(NormF_A, decimals = 5)

True

#### Cпособ №3

In [12]:
B = (D*D)
NormF_D = np.sqrt(np.array([el.sum() for el in B]).sum())
print(f'Норма Фробениуса для матрицы А:\n{NormF_D}')

Норма Фробениуса для матрицы А:
11.045361017187261


норма полученная при помощи функции __np.linalg.norm__ равна $$ \sqrt{\sum_{i=1}\mu_{i}^{2}}$$

In [13]:
np.around(NormF, decimals = 5) == np.around(NormF_D, decimals = 5)

True

In [14]:
if np.linalg.norm(A) == NormF:
    print('По умолчанию в функции norm используется норма Фробениуса')


По умолчанию в функции norm используется норма Фробениуса
